name: deploy to lambda
on:
  push:
    branches:
    - master
jobs:
  deploy-lambda:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            lambda_function.py
            requirements.txt
          sparse-checkout-cone-mode: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install requirements
        run: |
          pip install -r requirements.txt -t .
      - name: zip
        run: zip -r deployment.zip .
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws_region: us-east-1
          timeout: 120
          function_name: bourbon-finder
          zip_file: deployment.zip